version: '3.4'

services:
  sqldb:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - SA_PASSWORD=Foxford#@12432
      - ACCEPT_EULA=Y
    ports:
      - "1440:1433"
  backend:
    container_name: apex-backend
    image: apex
    build: 
      dockerfile: ./Dockerfile
    environment:
      - DB_USER_ID=SA
      - DB_HOST=sqldb
      - DB_NAME=apex
      - DB_SA_PASSWORD=Foxford#@12432
      - CLINET=http://localhost:8001
    ports:
      - 8002:4000
  frontend:
    container_name: apex-frontend
    image: frontend
    build:
      context: frontend
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
      REACT_APP_SERVER: http://localhost:8002/api
    ports:
      - 8001:3000
  proxy:
    image: nginx:mainline
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
  
